### ISSUE TITLE
Test CI run generates remap error

### ISSUE THREAD

**Issue by GenZodd** [antonybudianto/angular-webpack-starter#108]
## Issue Overview
When running test with ci enabled "npm test -- --ci" remap fails. 

## Issue Description
When running test with ci enabled "npm test -- --ci" remap fails. 

20 12 2016 10:12:40.132:ERROR [coverage]: TypeError: remap is not a function
    at RemapCoverageReporter.onCoverageComplete (D:\GitHub\angular-webpack-starter-master\node_modules\karma-remap-coverage\remap-coverage.js:23:23)
    at Server.<anonymous> (D:\GitHub\angular-webpack-starter-master\node_modules\karma\lib\events.js:13:22)
    at emitTwo (events.js:106:13)
    at Server.emit (events.js:191:7)
    at InMemoryReport.writeReport (D:\GitHub\angular-webpack-starter-master\node_modules\karma-coverage\lib\in-memory-report.js:14:22)
    at writeReport (D:\GitHub\angular-webpack-starter-master\node_modules\karma-coverage\lib\reporter.js:68:16)
    at D:\GitHub\angular-webpack-starter-master\node_modules\karma-coverage\lib\reporter.js:290:11
    at Array.forEach (native)
    at Collection.forEach (D:\GitHub\angular-webpack-starter-master\node_modules\karma\lib\browser_collection.js:93:21)
    at D:\GitHub\angular-webpack-starter-master\node_modules\karma-coverage\lib\reporter.js:247:16
    at Array.forEach (native)
    at CoverageReporter.onRunComplete (D:\GitHub\angular-webpack-starter-master\node_modules\karma-coverage\lib\reporter.js:246:15)
    at Server.<anonymous> (D:\GitHub\angular-webpack-starter-master\node_modules\karma\lib\events.js:13:22)
    at emitTwo (events.js:111:20)
    at Server.emit (events.js:191:7)
    at emitRunCompleteIfAllBrowsersDone (D:\GitHub\angular-webpack-starter-master\node_modules\karma\lib\server.js:294:12)

## Reproducables
pull down the project and run npm test -- --ci

## Information
|                      	|                                 	|
|---------------------	|---------------------------------	|
| **Operating System** 	| Windows/10 	|
| **Node version**     	| 6.9.2   	|
| **NPM Version**      	| 3.10.8    	|
| **Environment**       | Browser          |

**Comment by GenZodd** [comment]
So after I posted this I remember I had upgrade node after I did my npm install. I deleted my node_modules folder and run "npm install" again and now test with CI is working and generating code coverage data.
