### ISSUE TITLE
Dashboard errors and will not work sometimes with npm start

### ISSUE THREAD

**Issue by GenZodd** [antonybudianto/angular-webpack-starter#110]
## Issue Overview
Every now and again when I run npm start I get a dashboard error and node will not start and launch the site. 

## Issue Description
<Please explain the issue in details>

## Reproducables
Here is the error log. When I install a new package or move my TypeScript files around is when this tends to happen. I do an npm run build:dll but that does not change anything. 

webpack-dashboard -- webpack-dev-server --inline --port 8080

ternal/process.js:172
    throw errnoException(err, 'kill');
    ^

ror: kill ESRCH
  at exports._errnoException (util.js:1022:11)
  at process.kill (internal/process.js:172:13)
  at process.<anonymous> (<my folder path>\node_modules\webpack-dashboard\bin\webpack
ashboard.js:70:11)
  at emitOne (events.js:101:20)
  at process.emit (events.js:188:7)
  at process.exit (internal/process.js:146:15)
  at Screen.<anonymous> (<my folder path>\node_modules\webpack-dashboard\dashboard\in
x.js:31:13)
  at Screen.EventEmitter._emit (<my folder path>\node_modules\blessed\lib\events.js:9
20)
  at Screen.EventEmitter.emit (<my folder path>\node_modules\blessed\lib\events.js:11
17)
  at Program.<anonymous> (<my folder path>\node_modules\blessed\lib\widgets\screen.js
93:12)

## Information
|                      	|                                 	|
|---------------------	|---------------------------------	|
| **Operating System** 	| Windows 10	|
| **Node version**     	| 6.9   	|
| **NPM Version**      	| 3.10  	|
| **Environment**       | Browser          |

**Comment by antonybudianto** [comment]
Looks like windows specific issues, cannot do much about this, for the time you can remove webpack dashboard command from `package.json`

Also for every new packages you install, please run `npm run build:dll` to refresh the cache
