### ISSUE TITLE
Problems with 'npm run build' 

### ISSUE THREAD

**Issue by Denfie** [antonybudianto/angular-webpack-starter#122]
<GitHub issues are ONLY for BUG reports and FEATURE requests>
<Questions or support can be send to StackOverflow>
<PLEASE DO FOLLOW and fill the issue template below. Don't skip or remove any section>

## Issue Overview
I can start via `npm start` but it fails after running `npm run build` or `npm run serve:build`

## Issue Description
See my log file at the bottom.

## Reproducables
sry its not plunkr able. ;-)

## Information
|                      	|                                 	|
|---------------------	|---------------------------------	|
| **Operating System** 	| OSX	|
| **Node version**     	| 7.3.0   	|
| **NPM Version**      	| 4.0.5    	|
| **Environment**       | Browser       |

```

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'build' ]
2 info using npm@4.0.5
3 info using node@v7.3.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle angular-webpack-starter@2.0.0-rc.1~prebuild: angular-webpack-starter@2.0.0-rc.1
6 verbose lifecycle angular-webpack-starter@2.0.0-rc.1~prebuild: unsafe-perm in lifecycle true
7 verbose lifecycle angular-webpack-starter@2.0.0-rc.1~prebuild: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Test Version 0.1.0node_modules/.bin:/Users/denfie/.rbenv/shims:/opt/local/bin:/opt/local/sbin:/Library/Frameworks/Python.framework/Versions/3.4/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands
8 verbose lifecycle angular-webpack-starter@2.0.0-rc.1~prebuild: CWD: /Users/denfie/Test Version 0.1.0
9 silly lifecycle angular-webpack-starter@2.0.0-rc.1~prebuild: Args: [ '-c', 'npm run clean:build' ]
10 silly lifecycle angular-webpack-starter@2.0.0-rc.1~prebuild: Returned: code: 0  signal: null
11 info lifecycle angular-webpack-starter@2.0.0-rc.1~build: angular-webpack-starter@2.0.0-rc.1
12 verbose lifecycle angular-webpack-starter@2.0.0-rc.1~build: unsafe-perm in lifecycle true
13 verbose lifecycle angular-webpack-starter@2.0.0-rc.1~build: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Test Version 0.1.0node_modules/.bin:/Users/denfie/.rbenv/shims:/opt/local/bin:/opt/local/sbin:/Library/Frameworks/Python.framework/Versions/3.4/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands
14 verbose lifecycle angular-webpack-starter@2.0.0-rc.1~build: CWD: /Users/denfie/Test Version 0.1.0
15 silly lifecycle angular-webpack-starter@2.0.0-rc.1~build: Args: [ '-c',
15 silly lifecycle   'webpack --config config/webpack/webpack.prod.js --progress --profile --bail' ]
16 silly lifecycle angular-webpack-starter@2.0.0-rc.1~build: Returned: code: 1  signal: null
17 info lifecycle angular-webpack-starter@2.0.0-rc.1~build: Failed to exec build script
18 verbose stack Error: angular-webpack-starter@2.0.0-rc.1 build: `webpack --config config/webpack/webpack.prod.js --progress --profile --bail`
18 verbose stack Exit status 1
18 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
18 verbose stack     at emitTwo (events.js:106:13)
18 verbose stack     at EventEmitter.emit (events.js:191:7)
18 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
18 verbose stack     at emitTwo (events.js:106:13)
18 verbose stack     at ChildProcess.emit (events.js:191:7)
18 verbose stack     at maybeClose (internal/child_process.js:885:16)
18 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
19 verbose pkgid angular-webpack-starter@2.0.0-rc.1
20 verbose cwd /Users/denfie/Test Version 0.1.0
21 error Darwin 16.4.0
22 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
23 error node v7.3.0
24 error npm  v4.0.5
25 error code ELIFECYCLE
26 error angular-webpack-starter@2.0.0-rc.1 build: `webpack --config config/webpack/webpack.prod.js --progress --profile --bail`
26 error Exit status 1
27 error Failed at the angular-webpack-starter@2.0.0-rc.1 build script 'webpack --config config/webpack/webpack.prod.js --progress --profile --bail'.
27 error Make sure you have the latest version of node.js and npm installed.
27 error If you do, this is most likely a problem with the angular-webpack-starter package,
27 error not with npm itself.
27 error Tell the author that this fails on your system:
27 error     webpack --config config/webpack/webpack.prod.js --progress --profile --bail
27 error You can get information on how to open an issue for this project with:
27 error     npm bugs angular-webpack-starter
27 error Or if that isn't available, you can get their info via:
27 error     npm owner ls angular-webpack-starter
27 error There is likely additional logging output above.
28 verbose exit [ 1, true ]


```

**Comment by antonybudianto** [comment]
Thanks for the report, but I cannot reproduce it on latest master.
Did you use the latest master?

**Comment by Denfie** [comment]
Yes I used the latest version. It includes also some of my ng2 components.
You never changed your version Number before you are uploading a newer version. I get the newest version only by merging files.

**Comment by antonybudianto** [comment]
Can you share a repo for me to inspect? It's hard without reproducible

**Comment by antonybudianto** [comment]
@Denfie I got your invitation, I'll check it out soon

**Comment by antonybudianto** [comment]
Most likely AoT compatibility issue, you have code that's not AoT compliance

**Comment by Denfie** [comment]
which code parts did you mean? as example... but thanks for taking looks to
my code.

2017-02-07 16:36 GMT+01:00 Antony Budianto <notifications@github.com>:

**Comment by antonybudianto7** [comment]
@Denfie , Sorry I also don't know the part, you might want to consult to angular team / ask to stackoverflow

**Comment by Denfie** [comment]
I thought that you saw a specific code part. That's not a problem I will
debug more. But thanks for your help.

Antony Budianto <notifications@github.com> schrieb am Mi. 8. Feb. 2017 um
01:59:

**Comment by antonybudianto** [comment]
@Denfie  I'll keep this open so other people with similar issue can help

**Comment by Denfie** [comment]
**Solved problem** 
There was one component which was marked as deleted but still in folder. Without any connection to the model. After removing `*.component.ts / *.component.scss / *.component.html` was it possible to build again.
