### ISSUE TITLE
E2E test with protractor broken

### ISSUE THREAD

**Issue by Justus-Maier** [antonybudianto/angular-webpack-starter#131]
<GitHub issues are ONLY for BUG reports and FEATURE requests>
<Questions or support can be send to StackOverflow>
<PLEASE DO FOLLOW and fill the issue template below. Don't skip or remove any section>

## Issue Overview

```
[11:32:43] I/direct - Using ChromeDriver directly...
[11:32:46] E/launcher - Error: C:\ody\angular-webpack-starter-master\e2e\home\home.spec.ts:1
(function (exports, require, module, __filename, __dirname) { import { browser, by, element } from 'protractor';
                                                              ^^^^^^
SyntaxError: Unexpected token import
    at Object.exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:543:28)
    at Module.m._compile (C:\ody\angular-webpack-starter-master\node_modules\ts-node\src\index.ts:413:23)
    at Module._extensions..js (module.js:580:10)
    at Object.require.extensions.(anonymous function) [as .ts] (C:\ody\angular-webpack-starter-master\node_modules\ts-node\src\index.ts:416:12)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
[11:32:46] E/launcher - Process exited with error code 100

```

## Issue Description
ts-node fails es6 imports for protractor e2e tests.
What about testbundling for protractor?

## Reproducables
simply clone and reinstall repo (yarn.lock)
> yarn
> npm start
> npm run e2e

## Information
|                      	|                                 	|
|---------------------	|---------------------------------	|
| **Operating System** 	| Windows 7 x64 	|
| **Node version**     	| 7.5.0  	|
| **NPM Version**      	| 4.1.2    	|
| **Environment**       | Chrome/Firefox          |

**Comment by antonybudianto** [comment]
Thanks for the report, I'll investigate it

**Comment by antonybudianto** [comment]
@Justus-Maier , I've fixed it, please review it, thank you

**Comment by Justus-Maier** [comment]
```
1 spec, 0 failures
Finished in 1.616 seconds
```
It works, yes! Thanks for fixing it so quickly!!

Small question before you close this:
If one wants to run the protractor tests against the production build, one has to change the protractor config to match production ports. Maybe the protractor config should also read environment config?

**Comment by antonybudianto** [comment]
It's possible too, you can install it easily by loading dotenv into protractor.conf.js

**Comment by GhadeerHaddad** [comment]
hey @antonybudianto , how did you fix it?

**Comment by GhadeerHaddad** [comment]
and I am facing same error but with export
